
---
- name: Install Apache
  apt:
    name: apache2
    state: present
    update_cache: yes
  become: yes

- name: Copy Apache config using template
  template:
    src: httpd.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
  notify: Restart Apache
  become: yes

- name: Enable site config
  command: a2ensite 000-default.conf
  notify: Restart Apache
  become: yes

- name: Start and enable Apache
  service:
    name: apache2
    state: started
    enabled: yes
  become: yes
